Table 'micronaut.person_phone' doesn't exist
I probably need to do some mapping to avoid this error,
but it's a strange error. This table should not be needed with
the current settings.

[io-executor-thread-2] DEBUG io.micronaut.data.query - Executing Query: SELECT person_.`id`,person_.`name`,person_.`born_timestamp`,person_phones_.`id` AS phones_id,person_phones_.`number` AS phones_number,person_addresses_.`id` AS addresses_id,person_addresses_.`street` AS addresses_street FROM `person` person_ INNER JOIN `person_phone` person_phones_person_phone_ ON person_.`id`=person_phones_person_phone_.`person_id`  INNER JOIN `phone` person_phones_ ON person_phones_person_phone_.`phone_id`=person_phones_.`id` INNER JOIN `person_address` person_addresses_person_address_ ON person_.`id`=person_addresses_person_address_.`person_id`  INNER JOIN `address` person_addresses_ ON person_addresses_person_address_.`address_id`=person_addresses_.`id`
18:37:31.836 [io-executor-thread-1] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: SQL Error executing Query: Table 'micronaut.person_phone' doesn't exist
io.micronaut.data.exceptions.DataAccessException: SQL Error executing Query: Table 'micronaut.person_phone' doesn't exist
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findStream(DefaultJdbcRepositoryOperations.java:507)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findAll$6(DefaultJdbcRepositoryOperations.java:530)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$executeRead$18(DefaultJdbcRepositoryOperations.java:709)
	at io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager.execute(AbstractSynchronousStateTransactionManager.java:146)
	at io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager.executeRead(AbstractSynchronousStateTransactionManager.java:162)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:133)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeRead(DefaultJdbcRepositoryOperations.java:709)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findAll(DefaultJdbcRepositoryOperations.java:529)
	at io.micronaut.data.runtime.intercept.DefaultFindAllInterceptor.intercept(DefaultFindAllInterceptor.java:51)
	at io.micronaut.data.runtime.intercept.DefaultFindAllInterceptor.intercept(DefaultFindAllInterceptor.java:35)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:135)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:98)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:143)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.example.PersonRepository$Intercepted.list(Unknown Source)
	at com.example.PersonController.listWithRelationships(PersonController.java:47)
	at com.example.$PersonController$Definition$Intercepted.$$access$$listWithRelationships(Unknown Source)
	at com.example.$PersonController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:143)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.example.$PersonController$Definition$Intercepted.listWithRelationships(Unknown Source)
	at com.example.$PersonController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:592)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)